---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  namespace: code
  labels:
    app: code
    name: code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain